# ns-3 実験用設定ファイル (改良版)

# --- 基本設定 ---
nStations: 10
heavyUserPercentage: 100
<<<<<<< HEAD
radius: 15.0  # 大きくする(隠れ端末)
=======
radius: 30.0  # 大きくする(隠れ端末)
>>>>>>> a8ff1ea041e8387ee8e1d24a5840fc8401cb45f2

# --- トラフィック負荷 ---
heavyUserRate: 10  # Mbps
lightUserRate: 0
packetSize: 1400 #TCPのMSSは1460

# --- 無線設定 ---
txPower: 15  # APの送信電力 (dBm)

# --- 実験制御スイッチ ---
useTcp: true
useMinstrel: true
maxAmpduSize: 65535
rtsCtsThreshold: 65535

# --- 出力設定 ---
outputFile: "cu_0125_RSSI.csv"
simulationTime: 30.0
enableTxtOutput: true
enableNetAnim: false
verbose: false