# ns-3 実験用設定ファイル (改良版)

# --- 基本設定 ---
nStations: 15
heavyUserPercentage: 100
radius: 25.0  # 大きくする(隠れ端末)

# --- トラフィック負荷 ---
heavyUserRate: 10  # Mbps
lightUserRate: 0
packetSize: 1400 #TCPのMSSは1460

# --- 無線設定 ---
txPower: 15  # APの送信電力 (dBm)

# --- 実験制御スイッチ ---
useTcp: true
useMinstrel: true
maxAmpduSize: 65535
rtsCtsThreshold: 65535

# --- 出力設定 ---
outputFile: "cu_0125_RSSI.csv"
simulationTime: 30.0
enableTxtOutput: true
enableNetAnim: false
verbose: false